coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 50%
        threshold: 2%
        base: auto

    patch:
      default:
        target: 50%
        base: auto
        only_pulls: true

comment:
  layout: "header,diff,flags,components,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

  # Show changes in PR comments
  branches: null

github_checks:
  annotations: true

ignore:
  - "tests/"
  - "**/*_test.rs"

flags:
  unittests:
    paths:
      - src/
    carryforward: false
